---
- name: Set system hostname
  hostname:
    name: "{{ system_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ system_hostname }}"
    state: present
